mainapp/urls.py
from django.urls import path

from . import views

app_name = "mainapp"

urlpatterns = [
    # Urls for authentication automatically handled by django hence not added
    # Urls for home page
    path("results", views.search_result, name="search_result"),
    path("register/", views.register, name="register"),
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("<int:property_id>", views.search_property_page, name="search_property_page"),
    # Urls for landlord pages
    path("calculateproperty/", views.calculate_property, name="calculate_property"),
    path("landlordproperties/", views.landlord_properties, name="landlord_properties"),
    path(
        "<int:user_id>/<int:property_id>",
        views.custom_property_page,
        name="property_page",
    ),
    path("landlordenquiries", views.landlord_enquiries, name="landlordenquiries"),
    # Urls for tenant pages
    path("tenantenquiries", views.tenant_enquiries, name="tenant_enquiries"),
    path(
        "tenant/<int:user_id>/<int:property_id>/",
        views.tenant_property_page,
        name="tenant_property_page",
    ),
    path(
        "tenant_enquiry/<int:user_id>/<int:property_id>",
        views.send_enquiry,
        name="send_enquiry",
    ),
]

nobroker/urls.py
from django.contrib import admin
from django.urls import include, path

#Add url file of any app created
urlpatterns = [
	#Url for auth paths
	path('', include('django.contrib.auth.urls')),
	#Url for mainapp
	path('', include('mainapp.urls')),
	#Url for admin
    path('admin/', admin.site.urls),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    # Database Model for User Details
    """We can't remove the username completely with using Abstract User,
    so instead we leave it blank."""
    username = models.CharField(blank=True, null=True, max_length=128)
    mobile_no = models.CharField(max_length=10, unique=True)

    USERNAME_FIELD = "mobile_no"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.mobile_no

    """password_hash = db.Column(db.String(128))
	user_properties = db.relationship('Properties', backref = 'user_property', lazy='dynamic')
	user_enquiries = db.relationship('Enquiries', backref='user_enquiry', lazy='dynamic')"""


class Properties(models.Model):
    property_name = models.CharField(max_length=20)
    lease_type = models.CharField(max_length=5)
    furnished = models.CharField(max_length=1)
    address = models.CharField(max_length=20)
    rent = models.CharField(max_length=100)
    rooms = models.CharField(max_length=1)
    landlord = models.ForeignKey(User, on_delete=models.CASCADE)
    # enquiry = models.ForeignKey(Enquiries,on_delete=models.CASCADE)

    def __str__(self):
        return self.property_name

    """enquiries = db.relationship('Enquiries', backref='property_enquiries', lazy='dynamic')"""


class Enquiries(models.Model):
    property = models.ForeignKey(Properties, on_delete=models.CASCADE)
    enquirer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.property

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

CHOICES = [("landlord", "Give on Rent"), ("tenant", "Take on Rent")]


# Inherit the Default UserCreation form
class SignUpForm(UserCreationForm):
    mobile_no = forms.CharField(
        max_length=10,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    user_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
    password1 = forms.CharField(
        label=("Enter Pssword"),
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )
    password2 = forms.CharField(
        label=("Confirm Password"),
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta:
        # Use the custom User Model that we changed.
        model = User
        fields = (
            "email",
            "mobile_no",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )
        widgets = {
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
        }


class PropertyRent(forms.ModelForm):
    lease_type = forms.ChoiceField(
        choices=[("f", "Family"), ("a", "Anyone"), ("c", "Company")],
        widget=forms.Select(
            attrs={"class": "js-example-basic-single js-states form-control"}
        ),
    )
    furnished = forms.ChoiceField(
        choices=[("0", "Not Furnished"), ("1", "Fully Furnished")],
        widget=forms.RadioSelect(),
    )
    rooms = forms.ChoiceField(
        choices=[("1", "1BHK"), ("2", "2BHK"), ("3", "3BHK"), ("4", "4BHK")],
        widget=forms.Select(
            attrs={"class": "js-example-basic-single js-states form-control"}
        ),
    )

    class Meta:
        model = Properties
        fields = (
            "property_name",
            "lease_type",
            "furnished",
            "address",
            "rooms",
        )
        widgets = {
            "property_name": forms.TextInput(attrs={"class": "form-control"}),
            "address": forms.TextInput(attrs={"class": "form-control"}),
        }


class SearchForm(forms.Form):
    lease_type = forms.ChoiceField(
        choices=[("f", "Family"), ("a", "Anyone"), ("c", "Company")],
        widget=forms.Select(
            attrs={"class": "js-example-basic-single js-states form-control"}
        ),
    )
    furnished = forms.ChoiceField(
        choices=[("0", "Not Furnished"), ("1", "Fully Furnished")],
        widget=forms.RadioSelect(),
    )
    rooms = forms.ChoiceField(
        choices=[("1", "1BHK"), ("2", "2BHK"), ("3", "3BHK"), ("4", "4BHK")],
        widget=forms.Select(
            attrs={"class": "js-example-basic-single js-states form-control"}
        ),
    )

mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

# All views are here


# Views For Auth Section
def register(request):
    # The new form is used
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_group = form.cleaned_data["user_type"]
            group = Group.objects.get(name=user_group)
            user.groups.add(group)
            return redirect("login")
        else:
            return render(request, "registration/register.html", {"form": form})
    form = SignUpForm()
    return render(request, "registration/register.html", {"form": form})


# Views For Landlord Section
@login_required
def calculate_property(request):
    if request.method == "POST":
        form = PropertyRent(request.POST)
        if form.is_valid():
            # To save but not commit and hence we can add more values
            form = form.save(commit=False)
            form.rent = "5000000"
            # The whole user object has to be passed
            form.landlord = request.user
            # Finally commiting after doing changes
            form.save()
            # To for a reverse url/dynamic url
            return redirect(
                "mainapp:property_page", property_id=form.id, user_id=request.user.id
            )
        else:
            return render(request, "landlord/property.html", {"form": form})
    form = PropertyRent()
    return render(request, "landlord/property.html", {"form": form})


@login_required
def landlord_properties(request):
    properties_list = Properties.objects.filter(pk=request.user.id)
    return render(
        request,
        "landlord/lproperties.html",
        {"properties": properties_list},
    )


@login_required
def custom_property_page(request, user_id, property_id):
    property_details = Properties.objects.get(pk=property_id)
    return render(
        request, "landlord/property_details.html", {"property": property_details}
    )


@login_required
def landlord_enquiries(request):
    enquiries = Enquiries.objects.filter(enquirer=request.user)
    return render(request, "landlord/lenquiries.html", {"enquiries": enquiries})


# Views for Tenant Section
@login_required
def tenant_enquiries(request):
    enquiries = Enquiries.objects.filter(enquirer=request.user)
    return render(request, "landlord/lenquiries.html", {"enquiries": enquiries})


@login_required
def tenant_property_page(request, user_id, property_id):
    property_details = Properties.objects.get(pk=property_id)
    return render(
        request, "tenant/property_details.html", {"property": property_details}
    )


@login_required
def send_enquiry(request, user_id, property_id):
    p = Properties.objects.get(pk=property_id)
    e = Enquiries(enquirer=request.user, property=p)
    e.save()
    return HttpResponse("Enquiry Sent")


# Views for home page
def index(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            lease_type = form.cleaned_data["lease_type"]
            furnished = form.cleaned_data["furnished"]
            rooms = form.cleaned_data["rooms"]
            print(rooms)
            properties = Properties.objects.filter(rooms=rooms)
            return render(request, "home/results.html", {"properties": properties})
        else:
            return render(request, "home/search.html", {"form": form})
    form = SearchForm()
    return render(request, "home/search.html", {"form": form})


def search_result(request):
    return render(request, "home/results.html")


def search_property_page(request, property_id):
    property_details = Properties.objects.get(pk=property_id)
    return render(request, "home/property_details.html", {"property": property_details})


def contact(request):
    return render(request, "home/contact.html")


def about(request):
    return render(request, "home/about.html")

mainapp/templates/tenant/base_tenant.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<title>NoBroker Rent Portal</title>
		<meta name="description" content="Free Bootstrap 4 Theme by uicookies.com">
		<meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">

		<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/ionicons/css/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/flaticon/font/flaticon.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/fontawesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/select2.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/helpers.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

	</head>
	<body>
  

    <nav class="navbar navbar-expand-lg navbar-dark probootstrap_navbar scrolled awake" id="probootstrap-navbar">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('landlord.add_property') }}">NOBroker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-menu" aria-controls="probootstrap-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span><i class="ion-navicon"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="probootstrap-menu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('landlord.add_property') }}">Search</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('landlord.enquiries') }}">Enquiries</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}
    <footer class="probootstrap_section probootstrap-border-top">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="{{ url_for('landlord.add_property') }}" target="_blank">Search</a></li>
              <li><a href="{{ url_for('landlord.enquiries') }}" target="_blank">Enquiries</a></li>
            </ul>
          </div>
        </div>
        <div class="row pt-5">
          <div class="col-md-12 text-center">
            <p class="probootstrap_font-14">&copy; 2017. All Rights Reserved. <br> Designed &amp; Developed by <a href="https://uicookies.com/" target="_blank">uiCookies</a><small> (Don't remove credit link on this footer. See <a href="https://uicookies.com/license/">license</a>)</small></p>
            <p class="probootstrap_font-14">Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
          </div>
        </div>
      </div>
    </footer>

    <script src="http://thecodeplayer.com/uploads/js/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="http://thecodeplayer.com/uploads/js/jquery.easing.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.waypoints.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.easing.1.3.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
	  <script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>
  </body>
</html>

mainapp/templates/tenant/lproperties.html
{% extends "base_landlord.html" %}
{% block content %}    
    <section class="probootstrap_section" id="section-city-guides">
      <div class="container">
        <div class="row mb-3">
          {% block prev_properties %}
          {% for property in properties %}
          <div class="col-md-12">
            <div class="media probootstrap-media d-flex align-items-stretch mb-4 probootstrap-animate">
              <div class="media-body">
                <h5 class="mb-3">{{property.property_name}}</h5>
                <div class="row">
                  <div class="col-md-6">
                    {{property.address}}
                  </div>
                  <div class="col-md-6">
                    {{property.rent}}
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    {{property.rooms}}
                  </div>
                  <div class="col-md-6">
                    <a href="{{ url_for('landlord.custom_property_page', user = current_user.user_id, property_id = property.property_id) }}">More Details</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% endblock %}
          <div class="col-md-12">
            <div class="media probootstrap-media d-flex align-items-stretch mb-4 probootstrap-animate">
              <div class="media-body">
                <h5 class="mb-3">02. Service Title Here</h5>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
              </div>
            </div>
          </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

mainapp/templates/tenant/property_details.html
{% extends "base.html" %}
{% block content %}
   <section class="probootstrap-section-half d-md-flex" id="section-about">
      <div class="probootstrap-text" id="property-container">
        {% if message %}
          {{ message }}
        {% endif %}
        <div class="probootstrap-inner probootstrap-animate" data-animate-effect="fadeInRight">
          <h2 class="heading mb-4">{{ property.property_name }}</h2>
          <div class="row">
          <div class="container">
            <div class="row">
              <div class="col-md-6">
                <p>Address : {{ property.address }}</p>
              </div>
              <div class="col-md-6">
                <p>Rent : {{ property.rent }}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <p>ID : {{ property.id }}</p>
              </div>
              <div class="col-md-6">
                <p>Landlord ID : {{ property.landlord }}</p>
              </div>
            </div>
            <div class="row">
              <a href="{% url 'mainapp:send_enquiry' request.user.id property.id %}" class="btn btn-primary">Send Enquiry</a>
            </div>
          </div>
        </div>
        </div>
      </div>
    </section>
{% endblock %}

mainapp/templates/tenant/search.html
{% extends "base_landlord.html" %}
{% block content %}
  <!-- progressbar -->
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{{ url_for('static', filename='images/bg_1.jpg') }}');" data-stellar-background-ratio="0.5" id="section-home">
      <div class="overlay"></div>
      <div class="container">
          <div id="form-container-row" class="row">
          <div id="form-container" class="col-md-8 probootstrap-animate">
<form id="msform" action="" method="POST">
  <h3 style="color: white";>Enter Your Property Details.</h3><br><br>

  <ul id="progressbar">
       <li class="active">Name</li>
       <li>Address</li>
       <li>Rooms</li>
  </ul>
  <!-- fieldsets -->
  <fieldset>
    <h2 class="fs-title">PATIENT AGE</h2>
    <h3 class="fs-subtitle">First Step</h3>
<input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>
  <fieldset>
    <h2 class="fs-title">Diabetes type</h2>
    <h3 class="fs-subtitle">Second Step</h3>
  </br>
    <input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>
<fieldset>
    <h2 class="fs-title">Treament Type</h2>
    <h3 class="fs-subtitle">Third Step</h3>
  </br>
    <input type="button" name="previous" class="previous action-button" value="Previous" />
  </fieldset>
</form>
          </div>
        </div> 
        </div>    
    </section>
    <!-- END section -->
    <section class="probootstrap_section" id="section-feature-testimonial">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-12 text-center mb-5 probootstrap-animate">
            <h2 class="display-4 border-bottom probootstrap-section-heading">Why we Love NoBroker</h2>
            <blockquote class="">
              <p class="lead mb-4"><em>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</em></p>
            </blockquote>

          </div>
        </div>
        
      </div>
    </section>

{% endblock %}

mainapp/templates/tenant/uenquiries.html
{% extends "base_landlord.html" %}
{% block content %}    
    <section class="probootstrap_section" id="section-city-guides">
      <div class="container">
        <div class="row mb-3">
          {% block user_enquiries %}
          {% for enquiry in enquiries %}
          <div class="col-md-12">
            <div class="media probootstrap-media d-flex align-items-stretch mb-4 probootstrap-animate">
              <div class="media-body">
                <h5 class="mb-3">{{enquiry.enquiry_id}}</h5>
                <div class="row">
                  <div class="col-md-6">
                    {{enquiry.property_id}}
                  </div>
                  <div class="col-md-6">
                    {{enquiry.enquirer_id}}
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% endblock %}
          <div class="col-md-12">
            <div class="media probootstrap-media d-flex align-items-stretch mb-4 probootstrap-animate">
              <div class="media-body">
                <h5 class="mb-3">02. Service Title Here</h5>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
              </div>
            </div>
          </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}