mainapp/urls.py
from django.urls import path

from . import views

app_name = "mainapp"

urlpatterns = [
    # Urls for authentication automatically handled by django hence not added
    # Urls for home page
    path("results", views.search_result, name="search_result"),
    path("register/", views.register, name="register"),
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("<int:property_id>", views.search_property_page, name="search_property_page"),
    # Urls for landlord pages
    path("calculateproperty/", views.calculate_property, name="calculate_property"),
    path("landlordproperties/", views.landlord_properties, name="landlord_properties"),
    path(
        "<int:user_id>/<int:property_id>",
        views.custom_property_page,
        name="property_page",
    ),
    path("landlordenquiries", views.landlord_enquiries, name="landlordenquiries"),
    # Urls for tenant pages
    path("tenantenquiries", views.tenant_enquiries, name="tenant_enquiries"),
    path(
        "tenant/<int:user_id>/<int:property_id>/",
        views.tenant_property_page,
        name="tenant_property_page",
    ),
    path(
        "tenant_enquiry/<int:user_id>/<int:property_id>",
        views.send_enquiry,
        name="send_enquiry",
    ),
]

nobroker/urls.py
from django.contrib import admin
from django.urls import include, path

#Add url file of any app created
urlpatterns = [
	#Url for auth paths
	path('', include('django.contrib.auth.urls')),
	#Url for mainapp
	path('', include('mainapp.urls')),
	#Url for admin
    path('admin/', admin.site.urls),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    # Database Model for User Details
    """We can't remove the username completely with using Abstract User,
    so instead we leave it blank."""
    username = models.CharField(blank=True, null=True, max_length=128)
    mobile_no = models.CharField(max_length=10, unique=True)

    USERNAME_FIELD = "mobile_no"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.mobile_no

    """password_hash = db.Column(db.String(128))
	user_properties = db.relationship('Properties', backref = 'user_property', lazy='dynamic')
	user_enquiries = db.relationship('Enquiries', backref='user_enquiry', lazy='dynamic')"""


class Properties(models.Model):
    property_name = models.CharField(max_length=20)
    lease_type = models.CharField(max_length=5)
    furnished = models.CharField(max_length=1)
    address = models.CharField(max_length=20)
    rent = models.CharField(max_length=100)
    rooms = models.CharField(max_length=1)
    landlord = models.ForeignKey(User, on_delete=models.CASCADE)
    # enquiry = models.ForeignKey(Enquiries,on_delete=models.CASCADE)

    def __str__(self):
        return self.property_name

    """enquiries = db.relationship('Enquiries', backref='property_enquiries', lazy='dynamic')"""


class Enquiries(models.Model):
    property = models.ForeignKey(Properties, on_delete=models.CASCADE)
    enquirer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.property

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

CHOICES = [("landlord", "Give on Rent"), ("tenant", "Take on Rent")]


# Inherit the Default UserCreation form
class SignUpForm(UserCreationForm):
    mobile_no = forms.CharField(
        max_length=10,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    user_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
    password1 = forms.CharField(
        label=("Enter Pssword"),
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )
    password2 = forms.CharField(
        label=("Confirm Password"),
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta:
        # Use the custom User Model that we changed.
        model = User
        fields = (
            "email",
            "mobile_no",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )
        widgets = {
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
        }


class PropertyRent(forms.ModelForm):
    lease_type = forms.ChoiceField(
        choices=[("f", "Family"), ("a", "Anyone"), ("c", "Company")],
        widget=forms.Select(
            attrs={"class": "js-example-basic-single js-states form-control"}
        ),
    )
    furnished = forms.ChoiceField(
        choices=[("0", "Not Furnished"), ("1", "Fully Furnished")],
        widget=forms.RadioSelect(),
    )
    rooms = forms.ChoiceField(
        choices=[("1", "1BHK"), ("2", "2BHK"), ("3", "3BHK"), ("4", "4BHK")],
        widget=forms.Select(
            attrs={"class": "js-example-basic-single js-states form-control"}
        ),
    )

    class Meta:
        model = Properties
        fields = (
            "property_name",
            "lease_type",
            "furnished",
            "address",
            "rooms",
        )
        widgets = {
            "property_name": forms.TextInput(attrs={"class": "form-control"}),
            "address": forms.TextInput(attrs={"class": "form-control"}),
        }


class SearchForm(forms.Form):
    lease_type = forms.ChoiceField(
        choices=[("f", "Family"), ("a", "Anyone"), ("c", "Company")],
        widget=forms.Select(
            attrs={"class": "js-example-basic-single js-states form-control"}
        ),
    )
    furnished = forms.ChoiceField(
        choices=[("0", "Not Furnished"), ("1", "Fully Furnished")],
        widget=forms.RadioSelect(),
    )
    rooms = forms.ChoiceField(
        choices=[("1", "1BHK"), ("2", "2BHK"), ("3", "3BHK"), ("4", "4BHK")],
        widget=forms.Select(
            attrs={"class": "js-example-basic-single js-states form-control"}
        ),
    )

mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

# All views are here


# Views For Auth Section
def register(request):
    # The new form is used
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_group = form.cleaned_data["user_type"]
            group = Group.objects.get(name=user_group)
            user.groups.add(group)
            return redirect("login")
        else:
            return render(request, "registration/register.html", {"form": form})
    form = SignUpForm()
    return render(request, "registration/register.html", {"form": form})


# Views For Landlord Section
@login_required
def calculate_property(request):
    if request.method == "POST":
        form = PropertyRent(request.POST)
        if form.is_valid():
            # To save but not commit and hence we can add more values
            form = form.save(commit=False)
            form.rent = "5000000"
            # The whole user object has to be passed
            form.landlord = request.user
            # Finally commiting after doing changes
            form.save()
            # To for a reverse url/dynamic url
            return redirect(
                "mainapp:property_page", property_id=form.id, user_id=request.user.id
            )
        else:
            return render(request, "landlord/property.html", {"form": form})
    form = PropertyRent()
    return render(request, "landlord/property.html", {"form": form})


@login_required
def landlord_properties(request):
    properties_list = Properties.objects.filter(pk=request.user.id)
    return render(
        request,
        "landlord/lproperties.html",
        {"properties": properties_list},
    )


@login_required
def custom_property_page(request, user_id, property_id):
    property_details = Properties.objects.get(pk=property_id)
    return render(
        request, "landlord/property_details.html", {"property": property_details}
    )


@login_required
def landlord_enquiries(request):
    enquiries = Enquiries.objects.filter(enquirer=request.user)
    return render(request, "landlord/lenquiries.html", {"enquiries": enquiries})


# Views for Tenant Section
@login_required
def tenant_enquiries(request):
    enquiries = Enquiries.objects.filter(enquirer=request.user)
    return render(request, "landlord/lenquiries.html", {"enquiries": enquiries})


@login_required
def tenant_property_page(request, user_id, property_id):
    property_details = Properties.objects.get(pk=property_id)
    return render(
        request, "tenant/property_details.html", {"property": property_details}
    )


@login_required
def send_enquiry(request, user_id, property_id):
    p = Properties.objects.get(pk=property_id)
    e = Enquiries(enquirer=request.user, property=p)
    e.save()
    return HttpResponse("Enquiry Sent")


# Views for home page
def index(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            lease_type = form.cleaned_data["lease_type"]
            furnished = form.cleaned_data["furnished"]
            rooms = form.cleaned_data["rooms"]
            print(rooms)
            properties = Properties.objects.filter(rooms=rooms)
            return render(request, "home/results.html", {"properties": properties})
        else:
            return render(request, "home/search.html", {"form": form})
    form = SearchForm()
    return render(request, "home/search.html", {"form": form})


def search_result(request):
    return render(request, "home/results.html")


def search_property_page(request, property_id):
    property_details = Properties.objects.get(pk=property_id)
    return render(request, "home/property_details.html", {"property": property_details})


def contact(request):
    return render(request, "home/contact.html")


def about(request):
    return render(request, "home/about.html")

mainapp/templates/base.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<title>NoBroker Rent Portal</title>
		<meta name="description" content="Free Bootstrap 4 Theme by uicookies.com">
		<meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">

		<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css'  %}">
    <link rel="stylesheet" href="{% static 'css/animate.css'  %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'  %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css'  %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css'  %}">
    <link rel="stylesheet" href="{% static 'css/select2.css'  %}">
    <link rel="stylesheet" href="{% static 'css/helpers.css'  %}">
    <link rel="stylesheet" href="{% static 'css/style.css'  %}">

	</head>
	<body>

    <nav class="navbar navbar-expand-lg navbar-dark probootstrap_navbar scrolled awake" id="probootstrap-navbar" style="position: inherit;">
      <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:index' %}"><img src="{% static  'images/favicon.png' %}" href=""></img> NOBroker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-menu" aria-controls="probootstrap-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span><i class="ion-navicon"></i></span>
        </button>
        {% if request.user.groups.all.0.name == 'landlord' %}
        {% block mainapp:  %}
        <div class="collapse navbar-collapse" id="probootstrap-menu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:calculate_property' %}">Calculate Rent</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:landlordenquiries' %}">Enquiries</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:landlord_properties' %}">History</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </div>
        {% endblock  %}
        {% elif request.user.groups.all.0.name == 'tenant' %}
        {% block tenant  %}
        <div class="collapse navbar-collapse" id="probootstrap-menu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:tenant_enquiries' %}">Enquiries</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </div>
        {% endblock %}
        {% else  %}
        {% block not_login  %}
        <div class="collapse navbar-collapse" id="probootstrap-menu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:about' %}">About Us</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:contact' %}">Contact Us</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
          </ul>
        </div>
        {% endblock %}
        {% endif %}
      </div>
    </nav>

    {% block content %}{% endblock %}
    <footer class="probootstrap_section probootstrap-border-top">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="{% url 'mainapp:calculate_property'  %}" target="_blank">Home</a></li>
              <li><a href="{% url 'mainapp:landlordenquiries'  %}" target="_blank">Enquiries</a></li>
              <li><a href="{% url 'mainapp:landlord_properties'  %}" target="_blank">History</a></li>
            </ul>
          </div>
        </div>
        <div class="row pt-5">
          <div class="col-md-12 text-center">
            <p class="probootstrap_font-14">&copy; 2017. All Rights Reserved. <br> Designed &amp; Developed by <a href="https://uicookies.com/" target="_blank">uiCookies</a><small> (Don't remove credit link on this footer. See <a href="https://uicookies.com/license/">license</a>)</small></p>
            <p class="probootstrap_font-14">Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
          </div>
        </div>
      </div>
    </footer>

    <script src="http://thecodeplayer.com/uploads/js/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="http://thecodeplayer.com/uploads/js/jquery.easing.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/owl.carousel.min.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.waypoints.min.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/select2.min.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js'  %}"></script>
	  <script type="text/javascript" src="{% static 'js/index.js'  %}"></script>
  </body>
</html>